name: .::Build and Publish Libcrypto Package::.

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (patch, minor, major) or skip for no bump'
        required: false
        default: 'skip'
        type: choice
        options:
          - skip
          - patch
          - minor
          - major
      custom_version:
        description: 'Custom version (e.g., 1.2.3) - overrides version_bump'
        required: false
        type: string
      version_suffix:
        description: 'Version suffix (e.g., rc1, a1, b1) - optional'
        required: false
        type: string
      dry_run:
        description: 'Dry run (build only, do not publish)'
        required: false
        default: false
        type: boolean

  push:
    tags:
      - 'v*'

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcrypto-distribution
          path: dist/
